#!/usr/bin/env node
// app_theme.dart (fridge-mobil) -> src/styles/_tokens.scss
// Elle kopyalama yasak — bkz. CLAUDE.md kural #1.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const THEME_PATH = path.resolve(__dirname, '../../../fridge-mobil/lib/core/theme/app_theme.dart');
const OUT_PATH = path.resolve(__dirname, '../src/styles/_tokens.scss');

const source = readFileSync(THEME_PATH, 'utf8');

// Dart dosyasında iki ColorScheme bloğu var: _lightColorScheme, _darkColorScheme.
// Basit satır bazlı ayrıştırma: "key: Color(0xFFRRGGBB)," satırlarını yakala.
function extractScheme(src, blockName) {
  const startIdx = src.indexOf(`static const ${blockName} = ColorScheme(`);
  if (startIdx === -1) throw new Error(`${blockName} not found in app_theme.dart`);
  const braceStart = src.indexOf('(', startIdx);
  // eşleşen kapanışı bul (basit derinlik sayacı)
  let depth = 0;
  let i = braceStart;
  for (; i < src.length; i++) {
    if (src[i] === '(') depth++;
    if (src[i] === ')') { depth--; if (depth === 0) break; }
  }
  const block = src.slice(braceStart, i);
  const colorRe = /(\w+):\s*Color\(0x([0-9A-Fa-f]{8})\)/g;
  const out = {};
  let m;
  while ((m = colorRe.exec(block))) {
    const [, key, argb] = m;
    const hex = '#' + argb.slice(2); // ARGB -> RGB (alpha FF varsayılan)
    out[key] = hex;
  }
  return out;
}

const light = extractScheme(source, '_lightColorScheme');
const dark = extractScheme(source, '_darkColorScheme');

// AppColors.light / AppColors.dark bloğundaki storage/status renkleri.
// DİKKAT: Bu renkler tema-BAĞIMSIZ değil — dark varyantı koyu yüzeyde okunur
// olması için farklı (daha açık) tonlar kullanır (bkz. cerebrum.md Do-Not-Repeat,
// statusWarning ışık/koyu karışıklığı). Her iki varyant da ayrı çıkarılır.
function extractAppColorsVariant(src, variantName) {
  const startIdx = src.indexOf(`static const ${variantName} = AppColors(`);
  if (startIdx === -1) throw new Error(`AppColors.${variantName} not found in app_theme.dart`);
  const parenStart = src.indexOf('(', startIdx);
  let depth = 0;
  let i = parenStart;
  for (; i < src.length; i++) {
    if (src[i] === '(') depth++;
    if (src[i] === ')') { depth--; if (depth === 0) break; }
  }
  const block = src.slice(parenStart, i);
  const colorRe = /(\w+):\s*Color\(0x([0-9A-Fa-f]{8})\)/g;
  const out = {};
  let m;
  while ((m = colorRe.exec(block))) {
    out[m[1]] = '#' + m[2].slice(2);
  }
  return out;
}
const staticColorsLight = extractAppColorsVariant(source, 'light');
const staticColorsDark = extractAppColorsVariant(source, 'dark');

// selector: CSS değişkenlerinin uygulanacağı seçici (":root", "[data-theme='dark']", ...)
function scssBlock(title, map, selector) {
  const lines = Object.entries(map).map(([k, v]) => {
    const scssName = k.replace(/([A-Z])/g, '-$1').toLowerCase();
    return `  --${scssName}: ${v};`;
  });
  return `// ${title}\n${selector} {\n${lines.join('\n')}\n}`;
}

const out = `// AUTO-GENERATED by scripts/extract-tokens.mjs — ELLE DÜZENLEMEYİN.
// Kaynak: fridge-mobil/lib/core/theme/app_theme.dart
// Yeniden üretmek için: npm run sync:tokens

${scssBlock('Açık tema (varsayılan)', { ...light, ...staticColorsLight }, ':root')}

@media (prefers-color-scheme: dark) {
  html:not([data-theme='light']) {
${scssBlock('Koyu tema', { ...dark, ...staticColorsDark }, '&').split('\n').map((l) => '    ' + l).join('\n')}
  }
}

// Koyu tema (elle seçim) — html üzerinde VEYA maket önizlemelerinde herhangi bir
// alt-ağaç kökünde (örn. PhoneFrame) [data-theme='dark'] ile devreye girer.
${scssBlock('Koyu tema (elle seçim)', { ...dark, ...staticColorsDark }, "[data-theme='dark']")}

// Boşluk ölçeği (DESIGN_SPEC.md §3) — ara değer yasak
:root {
  --space-xs: 4px;
  --space-sm: 8px;
  --space-md: 16px;
  --space-lg: 24px;
  --space-xl: 32px;

  --radius-card: 16px;
  --radius-button: 12px;
  --radius-input: 12px;
  --radius-storage-icon: 14px;
  --radius-logo: 20px;
  --radius-pill: 999px;
}
`;

writeFileSync(OUT_PATH, out);
console.log(`✓ ${Object.keys(light).length + Object.keys(staticColorsLight).length} açık + ${Object.keys(dark).length + Object.keys(staticColorsDark).length} koyu renk → ${path.relative(process.cwd(), OUT_PATH)}`);
