#!/usr/bin/env node
// app_{tr,en}.arb (fridge-mobil) -> src/i18n/app-strings.{tr,en}.js
// Elle kopyalama yasak — bkz. CLAUDE.md kural #2.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const L10N_DIR = path.resolve(__dirname, '../../../fridge-mobil/lib/l10n');
const OUT_DIR = path.resolve(__dirname, '../src/i18n');

function convert(locale) {
  const src = JSON.parse(readFileSync(path.join(L10N_DIR, `app_${locale}.arb`), 'utf8'));
  const entries = Object.entries(src).filter(([k]) => !k.startsWith('@'));
  const body = entries
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  const out = `// AUTO-GENERATED by scripts/import-arb.mjs — ELLE DÜZENLEMEYİN.
// Kaynak: fridge-mobil/lib/l10n/app_${locale}.arb
// Yeniden üretmek için: npm run sync:strings
// Pazarlama metinleri (hero, SSS, hukuki) için src/i18n/marketing.${locale}.js kullanın.

export const appStrings = {
${body}
};
`;
  writeFileSync(path.join(OUT_DIR, `app-strings.${locale}.js`), out);
  console.log(`✓ ${entries.length} anahtar → src/i18n/app-strings.${locale}.js`);
}

convert('tr');
convert('en');
