-- AI Chef sohbeti şeması -- 29-assistant-conversation.sql'de assistant_
-- conversation/assistant_message'a genelleştirildi ve chef_chat_message
-- DROP edildi (bkz. plan §A2). Bu dosyanın içeriği idempotent no-op'a
-- indirildi: migrate.js her deploy'da TÜM .sql dosyalarını yeniden
-- çalıştırıyor (bkz. migrate.js:22-30), dosya boşaltılıp silinirse migrate
-- sorun çıkarmaz ama numaralı sıra bozulur -- bu yüzden dosya kalıyor,
-- içeriği boşaltılıyor.
